### ISSUE TITLE
Fix some bugs in 2.1, split PackedAvroScheme to its own file

### ISSUE THREAD

**Issue by kkrugler** [ScaleUnlimited/cascading.avro#4]
I updated the 2.1 branch with some bugfixes and changed the unpacked api to use a different scheme for clarity. I think this should be version 2.1.1 and we should put a new jar up on conjars. 

Apologies for the diffs, new IDE and some cut/paste seems to have moved everything around.

**Comment by kkrugler** [comment]
Hi Chris - can this be closed now?

**Comment by ccsevers** [comment]
Yes definitely. Closing now.
